# Generated by Django 2.2.7 on 2019-11-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stretch_goals', '0003_auto_20191107_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='goal_number',
        ),
    ]
