# Generated by Django 2.2.7 on 2019-11-10 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stretch_goals', '0006_auto_20191109_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='datetime',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
