# Generated by Django 2.2.7 on 2019-11-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stretch_goals', '0007_auto_20191110_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('goal', 'date')},
        ),
    ]
