# Generated by Django 2.2.7 on 2019-11-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stretch_goals', '0008_auto_20191111_0012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
    ]
